FROM flightctl-base:latest as build
FROM registry.access.redhat.com/ubi9/ubi-minimal as certs
RUN microdnf update --nodocs -y  && microdnf install ca-certificates --nodocs -y

FROM registry.access.redhat.com/ubi9/ubi-micro
WORKDIR /app
COPY --from=build /app/bin/flightctl-worker .
COPY --from=certs /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem /etc/pki/ca-trust/extracted/pem/
CMD ./flightctl-worker
