FROM registry.access.redhat.com/ubi9/go-toolset:1.21 as build
WORKDIR /app
COPY ./api api
COPY ./cmd cmd
COPY ./deploy deploy
COPY ./hack hack
COPY ./internal internal
COPY ./go.* .
COPY ./pkg pkg
COPY ./test test
COPY ./Makefile .

USER 0
RUN make build
