{{ if .Values.flightctl.api.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    flightctl.service: flightctl-api
  name: flightctl-api
  namespace: {{ .Values.flightctl.api.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      flightctl.service: flightctl-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        flightctl.service: flightctl-api
    spec:
      containers:
        - name: flightctl-api
          image: {{ .Values.flightctl.api.image }}
          imagePullPolicy: {{ .Values.flightctl.api.imagePullPolicy }}
          env:
            - name: HOME
              value: "/root"
          ports:
            - containerPort: 3333
              protocol: TCP
          volumeMounts:
            - mountPath: /root/.flightctl/
              name: flightctl-api-certs
            - mountPath: /root/.flightctl/config.yaml
              name: flightctl-config
              subPath: config.yaml
              readOnly: true

      restartPolicy: Always
      volumes:
        - name: flightctl-api-certs
          persistentVolumeClaim:
            claimName: flightctl-api-certs
        - name: flightctl-config
          configMap:
            name: flightctl-config
{{ end }}
