{{ if .Values.flightctl.worker.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: flightctl-config
  namespace: {{.Values.flightctl.worker.namespace }}
data:
  config.yaml: |-
    database:
        hostname: flightctl-db.{{ .Values.flightctl.db.namespace }}.svc.cluster.local
        type: pgsql
        port: 5432
        name: flightctl
        user: {{ .Values.flightctl.db.masterUser }}
        password: {{ .Values.flightctl.db.masterPassword }}   # we should funnel this via secrets instead
    service:
        address: :3333
        baseUrl: https://{{ .Values.flightctl.api.hostName }}:3333/
        altNames:
          - {{ .Values.flightctl.api.hostName }}
          - flightctl-api
          - flightctl-api.{{ .Values.flightctl.api.namespace }}
          - flightctl-api.{{ .Values.flightctl.api.namespace }}.svc.cluster.local
    queue:
        amqpUrl: amqp://user:pass1234@flightctl-rabbitmq.flightctl-internal.svc.cluster.local:5672/
        managementUrl: http://127.0.0.1:15672/
{{ end }}
