// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+y9jXLcNpYo/CpYzn7lONtqWY4nlVHV1JZGthN98Y9KLWVqN+3doEl0N1YkwACg5E6u",
	"qu5r3Ne7T3ILBwAJkmA3W9afJdZUTeQmfg/OOTj/+DOKeZZzRpiS0f6fkYyXJMPw50GepzTGinL2hl38",
	"ggX8mgueE6EogX+R6gNOEqrb4vS41kStchLtR1IJyhbR1ShKiIwFzXXbaD96wy6o4CwjTKELLCiepQSd",
	"k9XOBU4LgnJMhRwhyv6HxIokKCn0MEgUTNGMRCM3PJ/pBtHVVeuXkb+RSU5iWGyafpxH+7/+Gf2rIPNo",
	"P/rLbgWHXQuE3QAErkZNEDCcEf3f+rZOlwTpL4jPkVoShKuhqkU7mAQW/WfEGemxxKMML4i3zmPBL2hC",
	"RHT16erTBlgorAp5Ci30SRZZtP9rdCxIjmFZo2iisFDmz5OCMfPXGyG4iEbRGTtn/FLv5pBneUoUSaJP",
	"za2Nos87euSdCyw0OKSeorUGf87WR28RrW/Vqlqf3DJbH6p1tz55G6mDSk6KLMNiFQbZTwSnarmKRtFr",
	"shA4IUkATFuDpj5nNUdnE2/yzjYBqNQblMvVACjU8pCzOV208Vt/QzF8HEejBkngQi0dkALdAA6jNmPQ",
	"3c5O3nX00l9ClCPI7wUVJNHgKyeuBgsRwT+wipftaeBnRCXCDJGUAEuiDM3gZ0l+LwiLSXu3Kc2o0n/0",
	"o9hjImLCFF4QIPOMMpppPNorF0qZIgtDwqNIkpTEigs9wbph3+EZSSeuse5YxDGR8nQpiFzyNNk0gL+u",
	"qy6gTSwUOoDnPqOEzCkjElhfSqXSbBDgqH/jaEYQ+UziQnN0ytbAVnrzUUUyuWkX5mivRhquR6ZDBVgs",
	"BF4BbJTAiixWgfupgVFlyxAeHR6fnRDJCxGT95xRxcV290uoMxz6oYbAXBMomdCFZnEnGhBSteHe2RQJ",
	"kgsi9YQII2F/nHOBMJJ0wUiC4qovmguewXEdHrTpOae/ECFhwhZtHh/Zb7VDvzC/kQSZzZp7kMpqVcB8",
	"9M+YIQPSMZoQoTsiueRFmmj+ckGE3knMF4z+UY4GSAS4hZXelaYYwXCKQGgYIcwSlOEVEkSPiwrmjQBN",
	"5Bi954IgyuZ8Hy2VyuX+7u6CqvH5D3JMuT6trGBUrXZjzpSgs0JxIXcTckHSXUkXO1jES6pIrApBdnFO",
	"d2CxDDjqOEv+IuzZyhCnO6csaYPyZ8oSYD/ItDRLrSCmf9KbPnkzOUVufANVA0DvyCtYajhQNifCtCzP",
	"mbAk55Qp+EecUs3tZDHLqJIOWzSYx+gQM8aVptkiT7AiyRgdMXSIM5IeYkluHZIaenJHgywIy4wonGCF",
	"N3GGjwCi90Rh4ACWUNf16CQtQ6iajegr8/rDmO6tS6yiNosp3ibtyoPcqGued3QrxqGbGzR0nLubHQ2c",
	"4pY5RXnp1WH5btPJ6Ku014XZfbZX7Xtz4Ft3z7f0URuutR2fMKe/FaNw0kv9eP8pcJ4TgbDgBUsQRoUk",
	"YicWRMMUHU5ORijjCUlJgjhD58WMCEYUkYhygCXO6diTNOT4Ym+8fglNrkI+51QYPY3EXMOztUjb3VgI",
	"SoZxgVOaULUCsQfwpZo3GkVzLjKsjMT93cuoLYCPIvJZCbzOvFESWeuAm8TTsHvogRFWBrOIdIYCDVyk",
	"llghB2EQyjSUc54XKfw0W8GvB8dHSAK5aMhDe71xzdNolhUKz9KAicRgUVCYPF0SNMOSfP9qh7CYJyRB",
	"x2/eV3//fDj5y94LvZoxeu/E+SVB+k4alyImJSmI9dhHhnVyquEI/oHMViqoIoLgKj4ETS5HLDEIBksS",
	"JUKYPobVA5f6vcApnVOSgIUmNE1BA2zu7Oj17R+StwaJFySA6WfwO4BcbwLYLoHL4JyskOnl7Z4yWAWV",
	"sqhL/LUbYiPy6h2HLV0fPCvX7cOlwQNFKYd4mLEdzytluC5swnku+AVOdxPCKE5355imhSDISH9u67BJ",
	"vXh9W2DKZADsWs+iWoxZIfKZSiVbnM7nT0HqtAO2FbhRBTXEtQpeArwPXWmuCuwtAInD8puxYupT5T6N",
	"jdHPjF8yFHsNBUEHADeSjNBrwqj+rwbPW0xTWFOJe/105XIV0dUnzUvnuEg1B7tqIWsDRbytBRGjHLd7",
	"49WZJkRhmkq4TzgjCGsyVA4H4kIIEEeUPmknx2pEd5p+wHqEpToVmEmY6ZR2GZN1O6RoRsxM5dJU2Zck",
	"RkjS67K4qTjCjKslEWMfC7Q0tFO3n/tyidQ8pL2Kn4oMMyQITgDJbDtEDaFoIc9BB894oeyKy+WNQ5Px",
	"GbCA5EfCiLm2w7sfO8FmvChbGkZTh8YllsAN9SWWoCI30/r3/Pevgve8IFiGJv9mJiiZP0fmeyVHuBmf",
	"yV777KkpulGdZuhG6tkNTJ9N/LfWVruCUQjhyu1Xp7+WVCqe6Uzgp6LQw7zFqSRbG70b49qxGr+6oRs/",
	"+/bqOhy81TlOZAzf7k/DlWDVliUdgMWUmoun9g9Hv8dYSGg6WbEY/vh4QUSK85yyhbO+aij/oiVPDQmt",
	"elhvSk5i9/P7IlU0T8nHS0ag/WtyQWPymmitg0ot1OtO/eD3hgmephlhyt5p3iY7770+bUoIdbYoQXdC",
	"ci6p4mIVhJsGV+eHFnD9jyWg36aEqA5owzcHWwNKD/DmBx/85pe+h2BQa04Xzrnm9KR+Bv8fqQp0vxqt",
	"7/VzKTpPSCyI2qrzEUspI9eY9Sel8lA3gIHg7M1nraiH7TtTaIFI2QQZvgtMU0+QFCmYAmhG5Bhptm4b",
	"UIl++xbZ//22j3bQe8q0UrSPfvv2N5RZTePFzl//NkY76CdeiNanl9/pT6/xSt+77zlTy3qLvZ3v9nSL",
	"4Ke9l17nfxJy3hz9+/E0mrJJkedcaBlW3+BYI59e7G96zU4d0sKdsX98Q8aL8QgGogwt9aLLEckFESv4",
	"7bme+bed3/bRCWaLqteLnR9+A8jtvUQH7/VN/gM6eG9aj37bR2ABco33RnsvbWupQMzae6mWKAMomj67",
	"v+2jiSJ5taxd18csptljQtkiJY29/FABRV+DP3hdphEin3GWp2QfTaNv0YudH0Z73++8/M4cq4Zf6GY8",
	"LKTi2c27UUZN9JwYhck4PWHfmWmvcTKGVZSqqBy31WZNAoZBtFHf/F73uOTLlaQxTlECH8eDrXTwqgxe",
	"Fblb3cb9BWPb5xr+kpAca0ZrRX+0o5vCBo+GHtQR5RNUA3SnVUewUJHNiNADWWVTY9nlksZLUKahpzPm",
	"bJ5GKixUQJf/UM7i2iCngpW6TXh0T1fqd2bhSKPm4VkLnAGMt/Jyll4HWI9haR+kJqONB6kbaXHEMF2t",
	"yTrWABqeXElFMh86N6P0rQ8zascjbICKkd66ACEIS4ggSefF424di9CJu9hMNy/iZ5Ndrj7P2vVKnpL2",
	"Uhcnx4dvLDcNmiilkTKPXm+O4qiN5ffsXpevBbQXl3hfT7FYkIAxfVJaaA0kpV4NSuraBcqIWvKkDu9o",
	"VKquZ4yAdgdqqlZ3VidEEtXWDJtbDqywe7NHmrgFVZ0EJA1i9uPTjdEsUrdR2f7ee1mTahFfSN7GQFWS",
	"NnXz3AxFr1v89Yh6zVh+6CaWsm7QqGIdz5h0yktPq0Jw5nKK4Ndy3uDXajEdn70Vljt/R+ckXsUp+Ynz",
	"8+aG/0HmXPia/sFcEeH92zQ4ITPO/RbVD9uAoraU1tSBNs3VdA7jL7BrHG/NHnBCTrzqWz2Kw/wuB0Xk",
	"voM2vIPoFaJhtc4hHuOBxWOMtrsWOy/CawdymHE/Tpy5pHErZkE3DpdKEILgq1VeBDo7ebdZqDMDrl1I",
	"l/wdXkpD2Pw4MasKXr3w5TVddMYtJPCtOZaxXCG5xC//+v0+fjEej5/33Gh9zu5tl9bqjs3HedEPQeoD",
	"GUlhFCVUnn9J/4xkvC+KhkZoulPzIioHtavrC5vuxIl/YmETOQ4FVTTG6bVTKEIT+xka7a/V5KGv3oJC",
	"n90iQ99855Rn9mhhiKdTrrk2/Fa9745m7lPgEok7UjzcvOY7yq1DoP/cQf9Da3re8/6zbM6YN+zd2xZX",
	"9KjWvGGuNWvktbuwsWH999CwLYc2YAwDSftYwVJ+jJUWXuqxYhn+/I6whVpG+y//+v0oyk2jaD/6r1/x",
	"zh8HO//5Yudv+9Ppzn+Pp9Pp9NtP3/5riCe24h5aVGhu2mOe0rgnCzjzehiAX3VSd1fsjP/VN4qHVbAq",
	"jgY7WzmyfbXMoQSmqTFMxarAaRVdgdeY1vsQlDVu+BYds5YtJbO2JTGAJbht5tl69IaZq3/cTnkGAEdj",
	"8TMjGjgGg1d88Paldxeis47LbN5yzYal736nKV5L89YjaDV/QggoOP3CYLZgS+UsNca07W27tTzZQgbD",
	"iI6sMaTHAFX7klUk23CJpMMi72FlbVV1KojCROGD0T/6EoXgbKr1VlDzjrlbIrkDS7HlKy4G6+ZMSjdg",
	"Hl6byPoRwgbCeay+jeKYXxJBko/z+TWls9oqvFlb37yFBL7WZa/ap7ZJpfa5toPA94DkViOu4H1XtrDK",
	"t4nKpYncLQqagFGjYPT3gqQrRBOtmc5XntU3cI15Gm1Y6TnwWmgub6ITZs1hW1ingWMM540sTs4VOnq9",
	"zVAmFIKyhdl/eJ0fXSNkWvWfoKkr+yAp99FeRTcFtAScDYb7HFqagAHM8MIEOgKFGxYE5QnitEj0l8sl",
	"Ye53Z+eaEZTwS5ZyjclgvLJxtO0Td+0mJlxmY+if2UzZumTj1+1/tQFsyY3xzYYJvgbRm+SZtXVfj2e2",
	"h/B45ll+yl+bdJKPhfo4t397Zt/rMMjalN4Uga/+rMHODftz/WuLz/nCaUO3QvairTurpPNKz1NCFBJE",
	"FYKRxFDCnKh4qekCI2niiSBUb63EXqFYV85Nj3heL0B81NrHTBB8rklt7U5mKzT11zWNPPWghSqyKVc8",
	"gMXbNa1fuOIKp2GuDZ+8yITQTD3jqy1bekjQsQLkOug0Q6kBVKMAsjbPv7HhIG+h8vy+w94SKs9NylCb",
	"InOsll2WVgGRtyuk22ixxhlZ9PD1Mdff5jDHp3CoHZWigFkP0pRf4mDRiUCjeukJckFS0GX1Z5LoxdkO",
	"hj8Jnqb6HqKAILngC0FkwEW2ELzI/7HqtiWkeEZSdE5WIOblRGhERtBNA9rF1njzY7fi7RKxMvz5jOEL",
	"TFNIkAoekK0p4lGuAzoqe5aE4SoqGUiEI34yyg42TIk/N6YsWHuu8hg2zhkURAo/RcQygeiFprbuBZXp",
	"oG7uMswpNjE8HMW27M94ygC9XY9KfHPJdgnCENrJtXByQZBd7pTNuR19tkLYpOkUjKoxqkKGyx8hO2p/",
	"ynbQM/nMBEebrFb4KTM/maha89PS/AQRxPBDYn5I8EpCUK1vPtzb+dun6TT59leZLZNPQbNhlS9QVfdp",
	"lvVyLXYkES7mdR0zqsac2A5Xo2gh8ngHhGYoprNDusN5GowhsIA1w4XYayspoo23rSZrSqbYHECNLmZt",
	"a62Pgz99COx9coG9LXLaLsa33f1my6N0ZEkZ2beljJjcqBbOuS8u65FILUeoJRF+QixaYolmhDDk2ntX",
	"3IzzlGBmfQLw9UB1z3QAwokeHC4QrGxQsD/dJZa1mfpZuF2PkFhTfXOzN8Kc9VcRVM5BEvqSipBmgJoN",
	"zf6kOFhOVo6dtYxGHXJ7eZ698CIcVRVsVg+wajUZrob7DrUKHkkvZ1Zbfhjirx5pPZzwxbWZA+hm5py9",
	"hsZz2mr7TCIFUdjGv9rmDLEU7SljKcwEoSosfvU+abJyy4oMIQAnDZ99/4SbG2DqB01W7nL3rXiPLqmW",
	"qSvuTqWzCYOirrG5UgoAKFUC83ruryHb79g7whk6Gm4X2dDrcqgEkq1YUynJXI3WVxDxUaaFV+2aIuOt",
	"S4W0C2CQL+DBawIKtivy0dZO2zJfoZaaWcWliWErdfegUFB21FNcC7pO4R1F19WsSwU7UPzW20E1Qeeq",
	"eoEKdtYOaoSLZsdDlh3HvNsYY9qek1VXm+ZpdgzeHqrXDjrP3J9AQ48Lqlbd+zDVinosv3vYcpDgwsGd",
	"3Q4j6yrIAu1dHZaNttayssfVKHpLU2JdsgbXnTfLlm2CIIzMclcXaNHPf1Ub+rAcrvbzSTl27eczN5Fd",
	"YThYUksfhHUEAecppgwp8lmhb85O3+788Bxx0SxpZkdw/GlO005Op9u90d30T233Jr901WCUMRoJLY/B",
	"LGP0vpAgbREK+uE0gsVNI72iaWTWNI3G6LUxZYIkXjYaezlg8FM0sl0CqV8jY58Og0Rv75k0puiRZ8m0",
	"ywKDpgsDZ0VGBI3R0evmsgTnyqyqLbjxhHRP/X//9/+RKCfCpqJBqcAx+g9egEBrlmNCADItfs5xRlOK",
	"BeKxwim6pGqpNSyCwbv+BxHc1SJ48f2rV3C6WE6ZFsFimtke+v4Nd3r18sVzLVKrgia7kqiF/o+i8fkK",
	"zaxlFpVpSGN0NEdaZC6BNpoyCAmobwcshHqvWmSpgKYXOPaLHngG9W7nCp5JnhaKlL4Vh6KIM1/pRR+4",
	"IkaMKuuJgadBNwVhakaQVtIvBVWKhB3phSRiLdbwSyidd+NYE/IDlQQXZI7gN26v9a11Ont2WytoJkO6",
	"02CeHcyzZQ+glO1MsqbLzZphYcywia38VDerwc8DHd+7La06h17Km2HYg9HskRrN4HhPjAO/M/PNmAPK",
	"51b6OPkrNhXmD2uMbhDbs9HQZoMO+uXEnNQaf8lzLIpkeWqNMk397i5K7TSDHsP8uRnw5BbdiQFdNjPv",
	"43Z2MhNU1jcBCFqPEAEBFafpCtEqTK1qgZb4goAoD8V1YleZuAomKO2QULf6cml1wpbquZ3pq4yQ+/L8",
	"maQVnblNxvHIoX0vrl0n6y1tbVDKlcYnJOdlPFvQZjzHqSRNEPepd+qGdhmuheiIX/wm51BwUl+5GVfk",
	"OYSdmzKVvd6T0iPbNsGtBis7tivZUHWid9MifF4wdVxqgi6gabcVz3RsVUGbiUlZVSemdSM4zTJQFMpt",
	"ffNrdR6YqquWo0ISrfkBya5YjMyXcF0/w4RPyAV1EtqmikHl8lqdR12BgqOer+81Ulg3nrutSmUPLjQv",
	"1OWInfmsCthsRMXP16blgfaeWTNRRlQgNs17Kas3H9FrW8tLFM2I5QVPKHBuTaBcKE7uCx5lrJDjpGDw",
	"EmMNY/SPD/8lzVEkio5q3Fqq1cpMHT/9NBjMVgiLRZHBrV9I/ZtUmCVYJEguSZpqDqLw5zE6BcEc3oyw",
	"ljeJMluZ180kUU5zqDu/gGCbkUYnCrS9QpdEeM/JFSwhAmE0w3KJdmJjm/0c9ohecnH+mnZYwPRHEyPt",
	"op3NdgvpkhuEeX3SchhYaI/KaAXrZCi1WvT9Ua3spu+Jj/nmIr9+H6+i79XGda0r/3tQK/1bsTai0Q+S",
	"ejhSooAbpCrYHuR4NnyaJMFTC225RU68wxrOnbPhG/kc6fnBbIsVuAlIag36xvaqtyCxotIaqOHXcun9",
	"FeGasyXAjrcwBmNrChY+WpagBik3XmK2MAz3C8AcNtDyPIy7ZdXoLaW9GI9joUKPSUry/SvnSkGCc2Xe",
	"JQyIO1JecpF0uIPsVxPDW6ilcSj8dHp6bHLMNLvxA+bK4UJZZ+c0N3aFX4goUyoC6YPnNLcCp3vg5MLv",
	"EIoEVKnsBYnTdxNw0COrn/dauB78nKz6D64b9x2bnxPWlT10TtiNQL778ZlT++gMCHsbptp8v0cd5c9b",
	"3GWpVB4U6TV1HneSM1Cx53XU14ggVuKWOWcSwjKk4qJ6uQc4lEmaraU0jcNy9x2L+bKYz+nn9lTHWJQO",
	"1rOTd/ZRIJ5pZjtXNlx2hiV8HaMjhWLMrABB0O8FgewigTOiwPRaxEuE5f6U7Wog7iq+60x4/w6N/w6N",
	"p6xHZVJPzyiP685VC4dBXez0murzssaJ+1X67/vMSG+1GygPDp2jGKepvq7ilDPzyGwIi+CdNpNP14FP",
	"ejiDa0YA4yw1OdmuqxY64YGJ6nEid9BjdCbBGEwXSwXY7bDSiJ2gmsAdYxftpLzZyh2vtZojfRRalIWV",
	"mFcMqDTu1iVJc8N5wNNQ7sghij6a0u483sb0MPKPNYQwnY/A9y3EdkLmRMDDzRZ4ZQ1qW0UtUBsa5Tg+",
	"7xN40l02rvOZikB6OdSI6PsKdBk9EpC2bpWs7TpDm137oEfP0uNbr3IUSZhss/2p1dGtIPhB5jgmm406",
	"FipVj5E36Ubrs+1d7SAE1rqhPZC0nuHcPo438hRhGzkhCDr48JokY/Qmy9VqlxVpanM5naXfPtqBGFdL",
	"ygKv3cPnSjPaiJzvm+0hq1PFy3fbB9m2AdgGkHP9BB17+ov1pMyIRM4XYZWfFVNLomhcPYxRKRq+up9S",
	"qST4Ny+woLyQpUkfliHH6MCryIZXRlMBHq6vBT5Hf1bejRFyC7sKmuAVZUUottV+gfFnBMJAqPcsof43",
	"RvBYvwulqZJVgauUtQvsW5Hee5JesDIRkN4D0UoAqjLN1bxpY5CMSsRz/LtWd63X110qiptH/NzLbGUW",
	"j2W9nmsSG7cEOCuoNA5xxfUyBSUX5hpj5LNyIS9Vwm0J90MDFVOCIeZMUgmxbzCWXpb1blpLOXEgszut",
	"Vc2DfTv1EhLJQXjFTKul5NKZ3szh5lAp2oDEHb1zyZtrt14pwtiIYJ/lSRpQumAmUzInNkmYqoK0E5OF",
	"eUsUxOgRKliqhYEVL8x6BIkJLUFpdRPBM4QZIn4gZceLChmmjLLFkSLZoWZhbQRstylzp0o8k8VM6uPW",
	"3wDl7OrhOKrXHvShWFnY6gHu+N0GITat7OlQyF3bieVhEJcGljXHzEa6UxP7y5W7RUlUmMIggL0GvHoY",
	"dxQpmStUMCApliCeUeWZFCURFKf0D/OERG2hcLrGaIy+sbFkMxJjLZRR+AxOumXBwPbGq68AAgtPqBgD",
	"jZ5X+xHEgs7gZXNPZiOlqfFaO3FRBTxNzDunDF3sjff+ihJu4gSJ8uYwuE+ZIkwfo95EqXeFMOVbIhXN",
	"QJT91tAg/cO6OWOe6vODRRxCtEIZjaLnFQQYadfYRqIFHiFKmy2O+5XuCF0pjRusLVlYa0NHrShzT7vo",
	"1iOts33gCv77xj2L+poT+YEr+Hcw4tUEzGzzAnNDujBGjnJFn9r7kr3lzSZATMmEI9N1ry2DvofyuTdf",
	"/UNvwgsTaLGo6ptGuPplrxW1XDNoeDY4eOEbBmUZE1RzcBcNXLG2rYkhD8RrMcZVVZPzml6OqrF56HPl",
	"ZxEFC9y4p4VPaUakwlnevwhkQlJyza6LNS+aHiBzCcQlE66FOWHnNouR99ppafwx74iY6BZ03HxW2ZiK",
	"xuiE4GRHS1g9C/R8cYbXeyNn2+gtqIRiBEJNp9b+g5kvBnGxwEzzOHg2GSuy4EL/8xsZ89z8au6t56U8",
	"E/W20/hqkm0bKl53yUhQa/AizLBC/BK8tRAoaH7X0i+aQsTUrp5qGtnHDLseZPIFoKDzxIqLFn4wrS0S",
	"6CrRGZnsmfQCC6sC6lW8Yj9T57FmWV5pjOo55v7Wpo1OFq8Wjp/QgBOTYZKnRic0uSZBNh/2jRyg/3/y",
	"8QM65gAJsKuOo65LIrxGIzwqjnACwqxdzbh1T/B8XfxBk7MfExETpoJWluqbE2TsYdtnMGtMIK8am1Y1",
	"Ov6vb/ZevPhf4MP+919f7Pzt0/P/L1jq5cS+w9QsA977mvE6vrEe6qtRl7Hi5jzonRatq09BL6Xb5zZV",
	"1nvW/w4DcG2F41AmkXvkqlf1Y2h8zdrorQe+OrnR11s//f4qoW/7yFnNaB6wu1ZfyzIf+u+Wg8bjnguq",
	"rEk4yDFP1jiATnyHj5cy8yNVvjOIC32dgBmfVK+mDdH3QxbNk8+iqShou1Qar9/N5tNUA4eTaurf65k1",
	"5Tc65Mndf36NaJxGz/u15PZDqs0jTbVp8JzesYHNSPw+j//3bjyRy6rthlV35Ig0W2yXKOL793tmi3hd",
	"vjy3oz7Y3dYzcVL1QUqEOilCz+fWdtDWn5dFhtlOWZm9kUsF4NNjhwsJFV2GLVehtVayjl8Q4RWtwxdE",
	"aK0WSgSDn8w9QD2DxzDNxFrhRW8BBfZbYePIjxpvxIKPmpHgo3oc+LgeBj6dJv/WFQE+ivI12vypKQTg",
	"lHQ+tzsyzkJBFwsiZBCSxuZnnPMXpM+7NrXznthO4WL2bkTvmGr7qJvtNiJXbTLPah98sA1ex+hXJqRz",
	"kmrgzibejJ1tzFK83TgFVJ8j1QDIKHOuiAznuS3wcXh81km9x2cho7up5N2pSnZU+XY+gE6PQqeH4Krk",
	"XKsPYHeJrIru4rL6XQ4du9nE9teta4NS3QGJq8ApdRhwHLdbZ7iARkjoVmP00UUYmF9zCAMwSAICkOEi",
	"WxszKrYbKtDtnUawihDO8pSyxZGWXi9CpfdLLjoj6pIQVtpgoKve1x0wxj75MbXyQt62R/5RBXa8jutM",
	"ViwOiQrV12aVZi90DYJJbGCCieyHdE7PtKG4iWmFMAor2YIGU75XNShBg5ljMHN49LatocPredOmjmpo",
	"Z+wYqPV+TRa274rFW9+iwOkHo8WjNVo0OEiLWPONeTKhbDfKWtH9R/BWqWtha7RVPSoaVZgyE3UauvtN",
	"8D7jUyaLmetONQW+wfHSLKUxlgnIcCPoJRsJZMpsDJolj4eRq9NOyQ+87WPDS4Rt1Yb3dhk2/TP5AxfH",
	"WjHwejajil99mQUIX4/3rU3Ld4aQQ55ltCM734Q+QgO0xNJmqV5iCcdPkvDJu5F/XBOUVI7uxRyFBu8T",
	"MbiNKcvUGrGOe2LDHINqekPtlUpgRRar/jovFCKa2NCrDqtlszpQAwH9z87K5R6Rsi9FNmu/NO1yUOfD",
	"OJdPq0IMa1XnokoeTtqA6lHAqAneK3i5P/TA1gYVvtUFcgAh8ep0KYhc8nTjE8JejEzQVT+Ry2tlE+eC",
	"XmBFfiarYyxlvhRYku68YPPdaMhyeVz2fQjpwPUFbcrbtftGk8lP/VN3OwB/zbxD6R/ZBrfBLWUd6t03",
	"4hhcDuKa3MN1WXfVpkKcouuOsvcSNcYJVQhmRVWNaTFOXfH7hLNn7rlMZDJBvCjHniWg+xjyqwvQSMMu",
	"OK8jUhHLsMcgw/GSMtI51eVy1ZjAvqqn1zCN3mKaFoJUry2avAAqq4QZkuVqZUP5IROgfqNXaTYH6ASW",
	"ieIUCxMf6eJV7GY1YaBZoaFMTE4BvyBC0IQgqja8KRs8ThdJWgIPfYTEpX00jSaG/7nKzuVOb13415ry",
	"DmbJjnSvTvYg8lNb061TUW40qJvb/IhT5MrDDbEDg9lsMJthudsgne0sZ83ON2s8a4weDhYKNKpHDDUa",
	"DFFD926CC51IL1W0eQ8MlrhHaokLMaV24Zpwef3T8snsyyWXpLzxHX3OIcaBby5nYcbvs7zqifBeCQp+",
	"jdvRBn52HZNRuWPLpW4gcqh6tvDLbUYW180Lkn0y07axznzSx0Mz8p+ckXqN0nfcxF80wE0zgv7QylaZ",
	"uSSk9UnDzo8OPhy4bJeDkzcHu+8+Hh6cHn38MLKlkPSPdYHTJIPDcy0C8ZhgZli261mWmIT6klgoGhcp",
	"FkhSRcCiS1lZ6wGPETLvgBzAixV49wO5/O//4OJ8hN4U+lB3j7GgLnCgYDib0UXBC4m+24mXWOAYShe5",
	"bTbeC0HfTKMf359OoxGaRmenh9PoeYfh11h/JvGSJEXoRe3X3u0obStX3oprdI0tk5N+FQZFM1N7MUE8",
	"N4o7sqU+A/f0RqvToahXBwQ5RqgfBY6J/xR3X8uV8jBp7cXk2rU4YIiB6EaaivWoKY0JMzYfk5IUHeQ4",
	"XhL0cvwisqaDyPH+y8vLMYbPYy4Wu7av3H13dPjmw+TNzsvxi/FSZalZutLHFH3MCUOG46D3Ve3og+Oj",
	"aBRdOLEnKpgRbxKb88xwTqP96Lvxi/GeNYHDGehrZPdibxcXarlbpQ8tQpz4R6JMcbNaIk6ZwUw5O0r0",
	"hgvljBaQ6APFAmCyly9eNJ5P8hKidv/Hav3mEDYdkTcLHEAjy/hnve9Xez8EJMACXCyq3IWGEQxRg4Wt",
	"nkQ6ofGLbWBAYorQhUDh2gHUXTUxuFOoHmZJsCmb49Cl9YRaCY4mG/0UBm+DIUKZCdgNgOTFXlcbyqpW",
	"vQE3iv56g4dqnh8LnOeRlZiNqFY28w7Ne/HMvkTpRDOzk5SEXiM0v9fKG+gr8rAabGIGc2mqzRN+DQN0",
	"tpe3SQKletaF/uasb/dkzph9X+4PYhHsu9uf9C0XM5okhBkEvIMZ7QN+Z6y0ARrTFl7Ixnt7deyDANAg",
	"/wB9di3i1DFNS+Vrmze4SyC7217IZUOtlpo6h85XDO9mlYqP8RX4NYWs+Agj6AGg2oIpTqWajZ65IjrP",
	"bMETa4jNBbmAAk31ajJQuizaj2BBFT8sqy2t44SjUHkDU27GhtkpQWNVFYGBwBFb+8fVjzDVC6iw78PW",
	"HxIjF0SsyupboYWmtSpgd7dagK0cVZWrn/392Qg9+7v+fy2HPfuXvz8bw9tz6Jys9v4OZ7Q3Oierl/9i",
	"/vHyedeeYOzr7cmv4+6X+TEoVm7HLz5UFRY6rco/QZUcU9WmG6Vq3RGd1/EZHqYzgzbqOkG2xpKwVp34",
	"ikQgetOrmQQQ6sQBmkFmbAUn31X93cuQq/rTLd4QnfwCbG9rLo47uNL/gRPkvWs+XFYP5LLKuQxWFjPl",
	"vTyMQhalWjeVeXJ1nQxlR/sHT1a3j+sGQpUWp0RBru6D6LoJ7uUNIv9W07vXcWENL+9nDQdxTPJyET/c",
	"HHk0H/0OTp4KgpMV5CEL5bjCwP6eKPvrpVDu/qmv+6teemWAX6Jr6pKbRHw/VHP9tCC62PcUrORiC93W",
	"ueQ1jA/3xUGfCP28evHq9mf8wNVbXrDkK1auNVM3Kmwp1ce9bTonBCfXpsLKu+J5IAJk2Rr1y4lyFBWM",
	"/l4QW/QR5JyBTgc6fSB6hXuCtT4m+Mvg2UzjTmpQbX9LLFQTvJHLs3sfN3h19lWAdgBu/7bdCdYqK15Z",
	"/WdQd3x1ZxDyHw/ze/Xib7c/4SFn85SagJGvgNsWQakICoxem8WemP43raHcgii0JZMdrEwD2x3Y7sB2",
	"79B6tIvzXPCy+EqXGYmtrs2tXxO2+gpY9aC1DhzkCXCQTs+a4QPXF8oOTP+vRyh7SGQ9CCMDK9mGsiHi",
	"rs5Q7iv68V6ZmSfpGGP3daIsX9ueYT9Y9XUIoHz8TlmDRRuiJbsQ5h2Vqvo2xEEOcZAPJw7yAM1panEs",
	"uCPLP93jWTXUMV3tU1uF1Avf9jhMz7cwUG3l/V8yGUI7rxnaebMIDg+FbXv85nWxLTHWloFB8xQv4LFY",
	"+yY+1C3TIMsyLFb1XEI5Rv/U4Ibz5Ag0AVu2y54dHHetBBrwVjuYlwZpc98AK2D9zwwB1zjLM/9t/noO",
	"HDzm+swOrId6BmWSRNHJXL22IViVZXFuVYExN9gQmXt3UtAHrlwB5gcoB4XNBeZpS4StMNQRfFt+vA0f",
	"iB28l8Nj71ZmHdwL96HR35OC/YCIsq32bhML2kGxvrq7jbGu7PHQLXPdlDtY1x97TNgmvT4QqNlBJicE",
	"J/2IxPiT0EArA618rbTSESwJcX2uKEdJMEmYYKDx9tdKcuOk8mhCHTcT5yB9Dv6kxyPubhVG2HltQ+OH",
	"IN7eryZ8d2xo0LoHvjfwvdtQ83e9V/SD6oxFUFM0TrfU/2W24n2bNUJj99j+o9dq3EYH5Wag6QdE0wmB",
	"x0ykKxgclHnKEohefqfiqNa3bdirPj5m+cff50OThQbRZLDR3DE/EYQlBJC/Q0hY2JCHeZGmToEym4AC",
	"q72MOz8SdWLn8coPb2AvH27LzDPqfMnpnPFLhhxIqurRIS88tD1pNb0fkSUA3TUK16v2KX/gyC1k4AmD",
	"aHMvrKh69aHb+SJrr8ts4YaZuBdfBo/lQM2P0wuzzvq5Nd14dtCHQDpPxRo6aAADf7jta5eUpQZNbXQv",
	"Kqizkr5pCRK/6U7ZwsXStrhHVcuwrKy/sQqVYx82wTBBh5OTr+DubW11oOzHS9noQZF2k4y7iPwLXhao",
	"sLsr761VtnRIgXsaKXAt/NqQDVchClr7aEAQoYYkuSFJbngsYHgsYF297CEVabiNGrfR+scBqj7m4cK1",
	"KUrt8uy3Y5XoKAN/d4lLverQ1wrxDzXwh0SqR+myCDGVtRrWNulVbXm4r4a1jSE2OMvXY1MZSp09YdPl",
	"FhpmIC+rQqKgU3BrqjIFLtiCiFxQIzLUCWygr4G+HgF9bZFD0eMKs37EG7rDvoqay9eU4O+FvO9TcRhk",
	"9iGu6QkrCbWKyuuLp9iG7eCNEGcMllt90vz3wAH6vvlwfSGDlfKR88SXL+8CrrngMZFS86U3TFG1erp1",
	"Xm+AKX9JCOpmbhxUPLePrht0zoEhPR2d80vILax8PjCKe9oq6EDtT4vavWt4nhJyrbC0t6Zj2F9Sfhyi",
	"0B6/3x9QaEPkWQe2vKNSlZ+GALMhwGwIMBtKlt9JyXJXoBzSHsrjdZX1KUMEx0tkWFt4UpzYrEZ5yAum",
	"7q8KODDQIfJuuIE3VwB/a/E5FF3nvt2GMmTGvuMoOm/SwQE2BK3dAz229KzdP+G/V7uKZHmKlb7aJOXs",
	"OgqYGwKVY4R1sVPb7peq2VpJW4sZcKE6Obg10ThseZl7DOT+jZ2DgvhgrqcGsm9QFTfjtZZ1HjBWjwbd",
	"ddBdB931qSdHNTjUoKANN6B3A/YXDbdJaGheav1Ewi++O2/v6vQdgD1nfVAu9yakBxfcE3TB9ZZ/AykU",
	"Gyn6hODk66HnDwM9D/T8+Og5cJv3v7TDRlnPkb5NlMxb32PxgAmp0zg7kM9XnyTwUM2x/W/dMEnqq7YX",
	"QQYeXrhJuux0ZnY9tOxU9X7uzIkZ454dmgNveIpXq+fJ3OY9u3mQXqHt1jfo/KZv0EfzmN1GuhxsWIOc",
	"8Gict1ulYXcJDND2/oX4e43ouDMGNASPDAxvUIxuJk7ly1PxNuhQ2ycADaaNgYK/HvXlOul0m6WIB0A1",
	"T0OWGKj08VOpd+0JknNJFReUXCcW88TvHrbkN5oMcY+PP+qjRKrVhpBHsQ593lGpGsgzZMoN0YZDtOEQ",
	"bVh7fNLxmiHQcLhy3JWzIR3Max3OCTvxG9yG6O9NcMfZYc2ZByvfkCJ2X4TaoYhsE0S0hpQb+sdqG+tB",
	"bdiHbnhbT9KDXv/Y9fo++lYg2GcN6ZwQnAyEMxDO0yKcrUJv1lCPjU15OOTzaCJx+hHsILcO3umv2Dvd",
	"5Er9o3HW3ujQ4WvkSrenVd8tYxq0+IEbDtzw5gwGkhciJnLF4uu5Lk3/yYrFnaaDqsngu3wqhuQKrTZ6",
	"L72mYe9lDcUG7+XgvRSKsgUyqMKFBvE5CbkzEbgzR2gadXk0p9HzMXrLBcJoXqRpuZBqbD0W+YyzPCVy",
	"hASZG4SC/CgeFxlhCvB1cI0+oCKiep1h0Vuf3Zymellub7POtdQk9vsyrlXcb/DNDldqdaVu9M6uuVed",
	"f7Z2s96OLulNcec+2ubcg343eGnvj2S71K7tHLVrqLqtb21nnqoN/fC9Tuupe/A7PX6/Ux8lM+iyXUNE",
	"xmk7kNBAQk+RhLZ03q6hI+vQfFiE9IhcuP1IdxBrB7fFV+22aPKnbdy4a29568j9OvnTbSrgd82kBpV/",
	"4I0Db/xy68LVKDL2fsO8CpFG+9FudPXp6v8FAAD//8sJAtzxwgEA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
