apiVersion: v1alpha1
kind: Fleet
metadata:
  name: default
spec:
  selector:
    matchLabels:
      fleet: default
  template:
    metadata:
      labels:
        fleet: default
    spec:
      os:
        image: quay.io/redhat/rhde:9.2
      config:
        source: 
          - name: base
            configType: GitConfigProviderSpec
            gitRef:
              repository: flightctl-demos
              targetRevision: main
              path: /demos/basic-nginx-demo/configuration
          - name: motd-update
            configType: InlineConfigProviderSpec
            inline:
              ignition:
                version: 3.4.0
              storage:
                files:
                  - contents:
                      source: >-
                        data:,This%20system%20is%20managed%20by%20flightctl.%0A
                    mode: 422
                    overwrite: true
                    path: "/etc/motd"
        postHooks:
          - name: "Systemd Reload Unit Hook"
            description: "A hook that automatically reloads systemd units if updated in the watched path"
            watchPath: "/etc/systemd/system"
            actions:
              - type: "Systemd"
                triggerOn:
                  - "Update"
                timeout: "30s"
                unit:
                  name: "" # auto-discover from the file name if it is a valid systemd unit
                  operations:
                    - "DaemonReload"
                    - "Restart"
      resources:
        - monitorType: CPU
          alertRules:
            - severity: Warning
              duration: 10m
              percentage: 50
              description: 'CPU load is above 50% for more than 10 minutes'
          samplingInterval: 30s
      systemd:
        matchPatterns:
          - chronyd.service