// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/flightctl/flightctl/api/v1alpha1"
	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x963LcNtbgq2A5X5XtDLtbsp1Uoqqv8inyJdrYlkqXpGbc2jGaPN2NEQnQACi5k1LV",
	"vsO+4T7JFm4kSILd7Lasmf3i5IfVxO3g4ODccHDwR5SwvGAUqBTRwR+RSJaQY/3n4UywrJRwiuVS/U5B",
	"JJwUkjAaHURnUHAQqhnCFGFbF81JBqjAcjmO4qjgrAAuCej+imA/F0uoW6sqSDKETT+MIrkEJFZCQj5G",
	"75gEJJdYIkxXCD4RIQldmKq3JMvQDBC7AX7LiZRAFQTwCedFBtFBNLnBfJKxxQQXxThjiyiO5KpQJUJy",
	"QhfR3V31hc3+CYmM7uLosCgu9LcQ2Ko2YnMNIy6KjCRYlepxaZlHB+8NcgVEV+3R4ujTSFUa3WBOca4w",
	"9N6NduQaGQBcv0eMSqBSwYKz7GQeHbz/I/oPDvPoIPrLpF7GiV3DySuSgWt0F6+vewYZluTGLLaqzOFj",
	"STikCi69clcd9LTge0lvfsXcLHVj4aEuwGlKVF2cnTaqtJYibmH7Jb0hnNEcqEQ3mBM8ywBdw2p0g7NS",
	"kQ3hIkaEKrggRWmpukG8pJLkMEZqsa5hhTBNkWkBOFmivBRS0cwM5C0ARfu6wtNvn6FkiTlOJHAxjjrT",
	"7qETh4ZTzm5ICvy8gGT4WgXwqFahiUhcU+OGvnS1uzhSpNWz5+oBkapVYWP///7v/9PEAcoYXcRISMwl",
	"uiVyiTDKQErgiHFEy3wGPNa4SxiVmFBEGbpdEgmiwAmMB221PyJGYQCijnO8gD50b6LyY5oR2t/66u5q",
	"/dqeSyxLEeYIpkzxA4wEoYusiWPLy1K4IQYljkWcciiw5QnnCsXmz7OSUvPXS84Zj+Lokl5TdkujOFIM",
	"IgMJ6XC+0pyBP2an0AOiU1ZD1SlyYHYKarg7Rd5Emoj+lWWlodx6+zTR/QLmhIJAWFNvim50C1QKSNFs",
	"pWVSkyU3t1J4Y1xS8rEEsx8sY/f7VbRPaIjfd+nb5596sKvPpHmDkg7BhvDWZkHNqZsZie7s3xAhNf16",
	"ZGsrqzkSCbkYwHtaa1jvdcw5Xm3kn6aZoY/1u+xelvxdZ60D66mWcw4caAIhTcgWKc3F7PEiYytI0cnR",
	"8UjhKCOYSkTUKiqOqbbXHCcSzXByrQTV2rFDtOTDs4FlifMyzzFfDWRdWeYjUfSzrZ8BZ3K5iuLoBSw4",
	"TiENsKqt2VMT2nqM3ire4L11ApypWaEC9y6OjhTBzFU1OCcLxezO4GMJQnbR1lsVcU85Rtx+nKulR4Is",
	"KKQoqduiOWe5xvLRYZdqcUF+BS70iG0ADk+PbRlKLTvUpGS+QYrMrjTkTUQNlhVJc7VnDNWM0Tlw1RCJ",
	"JSszLcpvgKupJGxBye9Vb8KReYalmhahEjjFmdGsjB6Q4xXioPpFJfV60FXEGL1lHBChc3aAllIW4mAy",
	"WRA5vv5ejAlTbCUvKZGridInOJmVknExSeEGsokgixHmidIuEllymOCCjDSwVC/sOE//wkGwkicgglv5",
	"mtC0i8tfCE0RUetlalpFsUKZ26dnL88vkBvAoNVg0Fv0GpkKEYTOgZua1UoDTQtGqNQ/kowoxVaUs5xI",
	"4ehF4XmMjjClTOtlZZFiCekYHVN0hHPIjrCAL45KhT0xUigLIzMHiVMs8Sa5cKJx9BYkVq2EFUzrWvTu",
	"LqvpRaISEbt1Y5q3+au33yypeJO0kIdY7npwO+T2G8dFAUoWsJKmCCspxkcJB7XG6Oj8LEY5SyGDVLHg",
	"63IGnIIEgQjTa4sLMvZ4iBjf7I/XgtDlLPCpINwoY5AwmoqQaNPtjUlVMY0bnJGUyJXmaJqA64HVMHPG",
	"cyyjg4hQ+expTTWKUyyAK2zBJ8nxOoOwUjY6FNdUJjqWouoYYWloHYQT7Qq9xnfgcKwZrsJzwYoy059m",
	"K/318PQYCb2BFe51fTVzxdhInpdSWZ8Bu9DQUVBSKINrhgV893wENGEppOj05dv671+Ozv+yv6fAGaO3",
	"WCZLy8kVtY0r+UEgSxGhCPv0sE4IGSbVWJLZSkJoH2uxxN8FVaRjmhoi0zDxiiZMG8PxNef8WOKMzAmk",
	"WoMO8ouSBHjv5fGLB1gnDwiBFyEF+FJ/11hX09DCALRKfA0rZFp587emABGibEr0hra8kYDVlDfrpg+A",
	"mBYndNTcII7tWF+PEl8TFC4Kzm5wNkmBEpxN5phkJQckKo20mqXnXxA9eEdkXrsGRZfjeVXDe9R22dXR",
	"4hpxiClVv8L5oN2l2KtmcwFkHFVlRvNWK8v8nTZGvyjtFCVeRQ7oUKMO0hi9AErUvwpDrzDJDFCDzLVq",
	"8KCZ5lODN4UgDVQd9U+wXr4UJCaZ0AKEUUBYbTnpljspOdcKkVRr6pRXRdRnHktrLm2GhbzgmAo90gXp",
	"c3upekiSHMxIFWiyagupUdMUXJYMJUOYMrkE3lhtpY+NVF9hxUgoftGF4ucyxxRxwKmmJlsPEbMnlJrp",
	"sINnrJQW4gq8IENjM73d09dAwcjp8OzHTpMZL6qahqk0sXGLheZ8SmalqCzMsL5c/+55UK5zwCJoqaDH",
	"M05g/gSZGrXq4MZ8JAbNdKDS53p1Sp7raWAz4z5t7QDdQwVBHCK5CgH1+q/dLJu9HA0cxZoo2RxdcGVp",
	"vcKZgBhZ69U3zlV5FEe6wtbmeAs621frq+u69blhSTew2aVHe3pSUx3xDRtvNo7TGRPe/Wm4np6lYnmq",
	"MElACDLLoP3D8Y1TzIWuer6iif7jV6XLqhosy1gpj+kpZwsOQi3wpbK4rGO2gMRVfVtmkhQZnNxS4EJD",
	"ckMSeAHK2CJCmQ6q0TBkv6ScZVkOVFqZ6c2wV64OqVOhp7dGhbczKJggkvFVEGkKV70FHcz6hRWWX2UA",
	"0uFP/wjh2+DRw7r54OPefBm6AoYI52TRdogOc7u+JjLQfNMZwy+Vbn4OCQe5wwHFDqP+LGURaqZxUJRu",
	"Vd4yqha6ezbVlKa5qbb56LN2hDBkG21WLP3eg17x9QeV3ZmYWXJGX34qFC2F1RDOKIKqAjLSTAsi1Xda",
	"ZtrFQ3IQ4ylVk7Q1iEAfvkH2/w8HaITeEqpsywP04ZsPKLf22t7o2x/GaIR+ZiXvFD19pope4JVC2ltG",
	"5bJZY3/0bF/VCBbtP/Ua/wZw3e79u/GUnpdFwbgyAtRCYskUECNV8aAyKZVubNxaj2G8GMe6G0LRUoFc",
	"9Qc3wFf62xM17ofRhwN0humibrU3+v6DRtz+U3T4Vq399+jwrakdfzhA+iDBVd6P95/a2kJqHXX/qVyi",
	"XOPQtJl8OEDnEooarIlrY4Bptzg352vNuXxfo0RJze+9JlP60gQCKMyhvdH38f53o6fP7JIGFY2jUkiW",
	"G8ZyTOdsnbOiretoX47xyKYo0R0hu8HsAgSHbBujXieEGmLUZpxWC5te+Y6KYQDvAme+Nx3UxXIlSIIz",
	"r7+vPuivPuivPuhJrYAMtz1smx28y1e9+7hzcN491Q17kFrGpn+wvf4EW1sy6Sos/U3Ih1XelUWvyOx2",
	"SZKl9kzolmjQQbkaRseVBPjou2oUVwc5O7cyH8O9ewbpsDULh3jcxf1n5bWFZqtUx9B6k7Xg2u3ovG28",
	"9nhmqhNhtV4eQqvJD6Kr5oloSKoJU8HRz1IfzrbiBQIHxk0yJVaUriVTX9oZZ4jjfNpF4Mcn3Iu7YP1x",
	"eRvfG7Fq9PA+RB553q3axjf4UvtpThZdtHGgKXBIe8Xwma3gBG9vv5t8vs1x1k5SsKxXw7DFvqJhXRn6",
	"c8IohcRa/dVid+ctjLJ+/CLMiGwxOn7hO5RaI4QJw7R864mOFr1Xul41imPUjrUpuO3hwH82AhETTLW0",
	"FMaXSyiRBGfkd+N0rMJGgeeE4iyuYJbMNYsRyKRvuXB6QrNVdCB5CS3SbM0q9hDYv5S+3dxFhOvM6p3Y",
	"kVTatLYrb3VnDSXmC5DDxKYPyoVuF3bFmS6HTcnrp8vGq6Mes1mEGqEztRzkkqXNLeU7qC4paDeOdkYl",
	"kvHVGYgGfOtcQOsg9npeV605aoWFYyUHOZG9TN0yuxYvIq5Zd8afycxr00Uz8nqge2HjwUnbKe7Gydf0",
	"tcFnuwaHVeAnFqLpwKwjJS+pcPb8VlTUArgaIlhajRssrYHpKfYgrBD2hswhWSUZ7CT9Mtf6Xkmt3bkd",
	"+7MJrTXX3Sgs1Ekfafn3DUIYq9mRWznjXbZr3HSONr9sSWYtqNuk0ipuQBEoD4G2oVqD6E5EOMbGL0Wm",
	"aGY5vREg6OS80ht6eVwePMW7aHRiQjuNdcXR5dmbzZqW6befME7ETlvo5HzwFH5taopuGsF9oUtekEVv",
	"dEuqy9p9Gd8cEkv89NvvDvDeeDx+MhQ1zUH7EVUdOGyFrso9s0nGJUU5jB004XAGZErE9ee0zyFnfLV7",
	"D+1T/KKMqk4tdENRu/40QDSOAwyyjfOrGzH8G+Z2ox9xIkmCs51jh0OA+qHJ3dJ68FCpB1Co2AEZKvPP",
	"Pj3HUQ9bajElvMb5Whunw2L2C3sCtFPUfuvUqROtZCzJfkBM+Q4wBA+9QsMrU0n0RHc4bCSS3NS2oDWC",
	"hsPSNHGDQYdNkbW1caOjNgbCYeWbcZYZrhWwVxVojT1oj9nsitj4zeE4aB20hbBgLmamPba5KdSBaEQx",
	"2uYRYevAEctkeYqlBE6Dzie3sroiKmzNxmQ6/ipzSOTgKCmRWkTH5g4b4/pfpSWKcj4nn2JkAvSXkGUj",
	"IVcZoEXGZm4wDb8eHS8woUK6OKVshTKGUzBDaJhy/OkN0IVcRgdPv/0ujmwX0UH0v97vjX7Ao98PR38/",
	"mE5H/xhP9X/vp9Or/zGdjqbTb6bTH6/++vi/htV78uPj6XT83lQMFf9HSJpvvo9jHP2nLCPJQOFz6bUw",
	"5HrXK1f6RLVf6nuOwnq98K4CWeaJbNsca5OSZMZJnMgSZ3U42efyWqtq+Sy3Nim24C9dr35gj+Gub3Lr",
	"3lu+3eEBidUaaDwa77vz8yo8BqP1fPR+bhCiL28GMeza8aq0Vmey7uQ5UD1kWMhzADokmNCShYmdA+qC",
	"cS3/Gx45WNl0O5mhWwqWqk1DtGyra2phsA1xdgjScGl30D6gg7p+xa7SbThV2nNC5+2MBlTNnRiFN6aP",
	"Rp/8KjLWa1PDW2PNIzWfAvp1892PazxaXWKe3mIO+sDcxI0QurAiEzWOsO//GMfC4GJs788DeA9HOFtd",
	"mgy79050KFf4fuQZzBizQW6n7BY4pCfz+Y7GTwNWb9ROmQdIoLRp2jSKfHADxY0ZBMoDhlFjtw8Lqzkp",
	"3HGMoU7vjg98Kpiorz/gBVA5ntKXOFnqmxsJ4xxEwWhqYrlrldiQqQ0eSXCBZyQjcjWe0s0BOmYSDSpP",
	"WJaZFBRVlEWvqqGA7D3OU9LlcKHTXZgqwU3hB0709OHVUNLcRIhZPHXCh+qe1XqHDt1+Ykyi4xfbdGXi",
	"n4Zw9k7IlRJljikZbIdneVJxrnPHuQaC1w7P8BFaYaELRdxcvn4+0tGKN5xAFbqmdkrmmOKFuQ6g+aSR",
	"GTrNSZKVqSq5XQJ1313M1AxQym6ptUgUX7e3Srok6Oqdm/DHjfqGmUxVu5K7u7a/24C2dCcPqIHp/g+r",
	"Gt3fp7hqTHY3cdXtYoszhBph1QFCccFeYH2V6aSUJ3P7txeZvYucagDpDREo9UcNNm6FiDdLfXFDxPXG",
	"2Oetw43jf7N46SBHsZapZiWmA81MiLg2Nxm3SdCVEg76hLnK0OWcS6r7Zp/r57ImldSL0r+6NMdlpkyl",
	"PaUvdyHK8SeSl3l9LxlnGbv1I8NMdIlkKLFJZkweqKpBzS/dfc8UYR0Oy9TGvrFnuKDmaPuerZTNq+y9",
	"khI5RnXMdfVR3807QB+ECV8W5mZ1jD7k5oOJSFYfluaDjr3Wa1H7iB7/ePB+f/TD1XSafvPkx+k0fS/y",
	"5VXQlfOSJkzJgiHhDWDrGmrU0Sl6+bDErbBcnxkUGSZKGzL3lwdfazFDndrG7vdPtpO7uHvzpQt+p8qa",
	"xBr2IqlacBMysdbN8zWe+Ws8858wnrmzobYLbe42v98cGj2X4XA2gDW4qvUl47AuVzEKz1NpOYZOL9gb",
	"xobdpbs119lvlyCXwP3b22iJBZoBUOQ68NZ8xlgGmBpP4wyyz8mReOhyFZietKFbFNmqzkrVc1mks3h2",
	"nlutUK2qD9Or+pe6q9BsGHTTinvnBJ+79oc90Q9a/GNpY+D91b/ForHww1zArsVPfQH4zTh+VXeAHun1",
	"GvtTCqhj8ZZLsMNhTQDx1QKNg7QWNqCD1YzU8SqakTt1HwkXxaOPLwLhH4KHlyCUv8VPRSHMXVufpgIb",
	"uHkaNvxayZfgFy4NgD2wMCl1PRZCRHXEsQSKlFj1lpCIEIPr4TEKq4PYS58HoKfidnTY6aRv4xsBtBM7",
	"847cNiUf8Smqm4FkvHVekW4WDQhP+WEzhfhZiYN4SEyhWaM5CUWDJuvaa4MFSfgk0ePLi1ej758gxtvp",
	"l7xBdCg/yXoxrOo5+2UzHXjmWNDBpabff+tAlVb3DLrzXnBWFuFZqxk8EkjXiD2TFojWSLDLlGpT9gIn",
	"CTp+MUYvjKWt9YVpxBmT0yislbIU1g5dALfBLTp12Rj9jZVaWTfAGE9srlTrOc5JRjBHLJE4q1MKY22d",
	"/g6cuUu9e989f66XDxt+npDcNjB3EUJtnj/de6KsBVmSdCJALtQ/kiTXKzSzBjqqYpfH6HiOlDVQYSw2",
	"jtjmZLSNqeapeGCNMAVe+N5ZKYCvxRa71bmz7n2h+mhuO7fXNqnDGxS9qXIjqXwwz3i153rcROGsDJ37",
	"kAsizxQYoSXgfsZWjF4T2QySssmztvGQOb+YvYI0Jwt3S6jOrtFz/9EVb1b16q4ayd268T1apTmDG9J/",
	"usRtqQK6FF4S0rXwdq6LVcB3Ro37fH3rspL7s21FEg5OjWtXPjRwT5aMDvEoq38g9VD088XF6UD6UXs/",
	"/JyC+uooxmhZj4R52cAed0rmWRdOenGQJaf1OZcGRcANcM+96T2H8FnUx7vU54gH23SFK5qgNXRp4uxC",
	"k+eVJL48e2PT3LEcBMJzae1pJcB1aD06lvqGnTkHA/SxBO2Y5jgHna5elMkSYXGAptFE0eBEsolzDv2o",
	"a/+nrt3HP3spvFq+hydqR5GhkdemxN/lBYJQqvHOmUfPrYJONuzqiri9EhC4uo0KnFwPOj7ouzXRi5bT",
	"MsvqMMb6WOF4/o7JU2MrdA4YXKhBU+g+8ts8GqPflBWkbChVdpjd4pV4ZJQHM1EiUFFmmRLtOomJeYui",
	"0eqdKmk00q8w4Mxcodd5DPtTcJsxo7g9Gd3rQEe9wk/Vj/rR6kt9sv05lA7JMV8Rx8C09ueaaWxxSabb",
	"NhBN6t/4sQzL+Oc3JGYPCP4GGW2clEd1W+SO3wyYyf7KYUGE5KsxulBGuVKxZ2CiWho7TTU0aQur88eT",
	"o+Oqs1ix7YzRhfrXqkCM59VZhKprOhL+ieIQnrkuN/36Nzi+HLsygVFrQst9hmQF7C4XKGq1eb2ZbAEa",
	"yMv68oIdbD9PY8ZIZhPJdvnLoBlXNkUgZvfLisJexMXR2txrA1OmbA9mHAk92lB7o4YSmYaB+xCspHJH",
	"TbHhhzYDeNqg7rnho6unMQwhNczBDvSbP/296OKNXYVXvu4+9jB0tcnbaFvXixQinbf6TtyfIE+ed2rY",
	"jbGsypT2UuW7MG+uZRkqgAuic1/X9ye1xrLENxBbsrN6udAtDLQ6Ow63dQ3bCfhaKWWyvnuxo1u7rmwy",
	"2HaC8Dsr7/JjX5AchMR5seaMx1yD0EfTt1i4VNzDD3ZSyGCXsezrdrr5NuMt1iQEPkQCPpaaLdmETo2D",
	"eVyJfeQlC65Cx0ymDHNqgk7bGcjdk31ngNMRo9lqYP7gzz7VeIsLBaONN7iGlahffbNnHK3sLIwvMCW/",
	"mxj4BEtYMK5+PhYJK8xXARkk8okj5iAVDeOdNjAkmMP5loZchod+YASWiN3q9Oc68sR8j5U0mOpz9oka",
	"axrZzJV9+bZ0q/4AGIpYgT+W4JCohyWpIosqlMg4OB4JL1Klvk1eB8AMc0+eYpksvSCgSv8I08Bcpz1u",
	"MQ/Ws5Ns5K7xcxXAFWZ8Gwqnqb61UWRGrHDI2U3gvca7uMf5d4j+5/nJO3TKNCaqpy87rTUFhmE0UTFK",
	"NUhTpbRbaMYdgcCKdV61thbWeNJx7fudiNuq2z/feRhoe6/vdgqeTAhN4dP4n2IYOTnJd5gBl2c2Lrno",
	"v1nQndKyzDEdVUHBrWNk7bxQfYfPdMs+fuviG5VolY7Jq3l76hq+Aa4srlJYD0KV8W4Gc8btwIQuxuiV",
	"3uMH68MVH4lHzTjER/mjZhzio+Wj3jjE6TT9a3/oYQE8ASp702PU5QprZkbmkJmTxUKpAyFMGlFklOob",
	"GHJ5r7He57ZROI7a9egtU2MeTWlytYm4GoN1gy9taYdmHO8JpkHQFx+G+W56Yak77q3ijdhbx4DiTdpd",
	"BVdTJWqqOaHYfshxUdgD0qPTy95T5HAqahOo3Rv60BPE7ZT2vnb9Kv1dxdxW5smbhq6thPGgBOE9s9mk",
	"mq+Da0MQSA8m7q7WWA7dBVx7EyUcN44bJ04txd0x2nVpCXQlxFWtMTqh2co8/KG/FsCR25s6kMQwsK1T",
	"FdQcP5SsQEkUQhfHSk4HYworBu0eBHZB7rqpgvsBeG4V+N3HeNcYibG/FIEZhxjahicoiFEPZMmp1VMU",
	"4AnOXMRQyugjdxCFjLPRU5O/xl1/2bjrJBiUcV4uFuaJKn0gaBcncXEMGn8mECpGe4jYAAjjiBnweNvX",
	"YO97DfbueSdoiBrqX4BTeHTGTl9C5563eXKcLAmF3qFul6vWAGqhrQ9yqvMXllzZnTYNBjq2ABkSIAJB",
	"XkjtGeD6J2XN8LwbTDL9KBk6RGfmgaAkw9w+wmaP2IWL9k0BzUrFeUBoylU6NCcpICI3XMZbd4O7Rh46",
	"0a/sHKBpdF7qh0+mkbLLvJl+cbIRBSQjTNNRb7LCATH31VNFmk0MfJzoguTwd+aOENx56RtmlMWWmq9M",
	"mN+VIK/8A1xYYaiRenz47tC9o3F49vJw8ubk6PDi+ORdjG41MaiPzVs9CmGE6tg8jlgCmBo+7Fo2nucr",
	"MJckKTPMkSAS6he6lbHJAcfmEQljTaJDHU2FJ+/g9h9/Y/w6Ri9LJaAmp5gTp5aUFOczsihZKdCzUfUK",
	"vjHX1FxbEWTo8TR6/fZiGsVoGl1eHE2jJ0EqvOzclQ0/aK73ta1lrjaVkqmNklQXe7VCRtPQlWCpdPKF",
	"zedgL8wryFkZim7dmJW39aiK2UxcvuY4Af++3lql1dVTSplHXOvaVETYIfNQWNidzvVirvfqQ9BETwxy",
	"TLLoIJKA8/+aZ2SxlInMxoRFzl2n7dRXugQdqY3KMnQBOI/iqOSqqdvajdYdp+P7ZhdXj0PNnljhaKOr",
	"9c07UFzOeE/0dW/IbUzqPAOQmjVBunDnPMaVKZdAOLpl/FqRgjCpCjKSABVQn2pFhwVOloCejvc6k7m9",
	"vR1jXTxmfDGxbcXkzfHRy3fnL0dPx3vjpcwzs2BSu2FaSDo8PY7i6MYpc9HNPs6KJd63V/YpLkh0ED0b",
	"7433rctKE5zidJOb/Yn/cq2Jk3cyW/tqWPC1bXNaiQe+eFqx8+O0atz/tnf1dutPzDx64EUYe+fCk39a",
	"CWrodOe3hw3J1nQteQnGN1swtRSq46d7+w8FSAjRqVrK53t79wZDdVesM+BPOEUVPGrQ/QcY9JLiUi61",
	"q99O9dkDjPqK8RlJU6BmyB8eYEib15LReUaMhP/2QaZ6bhjdJa20O+OuxQvtvOplAdGVqraZU0z+UJzu",
	"Tsf6ggw5uHFaPaJsQqx7t0GXYbwGuY5b1NGG2km0/tBnM8NSZujC2F9E9WADoS0rrx748NlF7C1Q21dY",
	"UvKxhGPjOtG8xTiIGtxl71/DXU5++ZPt8ecPMOQ7Jl+xkqb/v+1uq9fYrTwxOcqSJSTX9sQpCQXAmFM8",
	"5NU2d4Wqt836tICf6xb2fbQtd3JrhHvdtqE9+jzwKhJDXoTZ13103/sI/Ws2EurbSWaLrN027tGeXlH4",
	"GqSN4LePBKWbdsprkO5Foc/aKWaDNAcX7XOG+9o/cW+OTp0QCLUeN6qG1VcC6nF15bPWQ0jb7dv7k60W",
	"+72C9N+YRzz4hn0YfbrWpLfbpbUXsk+u6eTS7UvKG4Wabta4Hf75Qk1DeK9ibahxPdJD/3W7xWoEEA0y",
	"rR9ug341ob+qBV9SLYijogyI/EubpnBbbnJmYs/umZ/UKQYfnKHstpO/8o8/g8qwQYDX2U2Ge6cpCiWt",
	"W++W7mbC+zIE3h3ngd3QPQB8dT//N3Y//8scz72is7OtN+36TZ5mZV5vufFfgwzt+q3kbP94X9wvtfew",
	"LOGrz/jPodQGd6aOBNfBYHpPmKPsibkma9p1XwqwW02/Rt5SR3Uojd0JVuh3HUfNHvo3mt9ZF/i7q7v/",
	"FwAA///4Z89RX6UAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	pathPrefix := path.Dir(pathToFile)

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(pathPrefix, "../openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
