flightctl:
  db:
    namespace: flightctl-internal
    image: quay.io/sclorg/postgresql-12-c8s:latest
    imagePullPolicy: Always
    password: adminpass
    masterPassword: adminpass
    masterUser: admin
    user: demouser
    userPassword: demopass
  api:
    enabled: true
    namespace: flightctl-external
    image: quay.io/flightctl/flightctl-api:latest
    imagePullPolicy: Always
    hostName: api.flightctl.example.com
  worker:
    enabled: true
    namespace: flightctl-internal
    image: quay.io/flightctl/flightctl-worker:latest
    imagePullPolicy: Always
    hostName: worker.flightctl.example.com
  periodic:
    enabled: true
    namespace: flightctl-internal
    image: quay.io/flightctl/flightctl-periodic:latest
    imagePullPolicy: Always
    hostName: periodic.flightctl.example.com

storageClassName: aws-ebs
storageClassNameRWM: aws-efs-tier-c4


# This is only related to deployment in Red Hat's PAAS
appCode: MYAPP
