flightctl:
  db:
    nodePort: 5432 # this is also mapped in /hack/kind_cluster.yaml as an extraPortMapping
    imagePullPolicy: IfNotPresent
  api:
    image: localhost/flightctl-api:latest
    imagePullPolicy: IfNotPresent
    hostName: localhost
    nodePort: 3333 # this is also mapped in /hack/kind_cluster.yaml as an extraPortMapping
  worker:
    image: localhost/flightctl-worker:latest
    imagePullPolicy: IfNotPresent
    hostName: localhost
  periodic:
    image: localhost/flightctl-periodic:latest
    imagePullPolicy: IfNotPresent
    hostName: localhost

storageClassName: standard
storageClassNameRWM: standard